sudo: false
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.5
  - python: 3.4
  - python: 2.7

notifications:
  slack: gazerteam:IIfxHoAw77Yf2bGcSRuTD46X

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create --yes --quiet -n gazer-test pip setuptools
  - pip install -r requirements.txt
  - source activate gazer-test
  - pip install coverage coveralls flake8 mock==1.0.1 nose


script:
  - flake8 gazer
  - nosetests --nocapture --with-coverage --cover-package=gazer ./tests

after_success:
  - coveralls