sudo: false
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.5
  - python: 3.4
  - python: 2.7

notifications:
  slack: gazerteam:IIfxHoAw77Yf2bGcSRuTD46X

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create --yes --quiet -n gazer-test pip setuptools nose pyqt numpy=1.10.4 pymongo=3.0.3 pyyaml scipy scikit-image
  - source activate gazer-test
  - pip install -e git://github.com/MichaelMauderer/python-eyex.git@v0.3.1#egg=python_eyex
  - pip install coverage coveralls flake8 mock==1.0.1 nose appdirs


script:
  - flake8 gazer
  - nosetests --nocapture --with-coverage --cover-package=gazer ./tests

after_success:
  - coveralls