sudo: false
language: python

matrix:
  fast_finish: true
  include:
  - python: 3.5
  - python: 3.4
  - python: 2.7

notifications:
  slack: sachi:cJEKEpgCGom3g10huT8XE1de

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create --yes --quiet -n gazer-test pip setuptools nose pyqt numpy=1.10.1 pymongo=3.0.3 pyyaml scipy scikit-image
  - source activate gazer-test
  - pip install coverage coveralls flake8 mock==1.0.1
  - pip install -e git://github.com/MichaelMauderer/python-eyex.git@874b390af27da8869816ee5f56ef131844a824ea#egg=python_eyex-dev
  - pip install -e git://github.com/MichaelMauderer/PyTribe@3de123848d876d96d9cd42a81d802d69c865e697#egg=pytribe-master


script:
  - flake8 gazer
  - nosetests --nocapture --with-coverage --cover-package=gazer ./tests

after_success:
  - coveralls